// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DataAccess;

namespace TaskAPI.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20230530094631_authorEntityAndData")]
    partial class authorEntityAndData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Pasindu Dilhan"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "shashikala Udeshani"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Minura Pabasara"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Manasa ayasankha"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Naween Ransara"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2023, 5, 30, 15, 16, 31, 104, DateTimeKind.Local).AddTicks(6088),
                            Description = "Get some text books for school",
                            Due = new DateTime(2023, 6, 4, 15, 16, 31, 105, DateTimeKind.Local).AddTicks(4324),
                            Status = 0,
                            Title = "Get books for school from DB"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Created = new DateTime(2023, 5, 30, 15, 16, 31, 105, DateTimeKind.Local).AddTicks(5062),
                            Description = "Get some bags for school",
                            Due = new DateTime(2023, 6, 1, 15, 16, 31, 105, DateTimeKind.Local).AddTicks(5066),
                            Status = 1,
                            Title = "Get Bags for school"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Created = new DateTime(2023, 5, 30, 15, 16, 31, 105, DateTimeKind.Local).AddTicks(5072),
                            Description = "Get some shoes for school",
                            Due = new DateTime(2023, 6, 4, 15, 16, 31, 105, DateTimeKind.Local).AddTicks(5073),
                            Status = 0,
                            Title = "Get Shoes for school"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
